# Sonata Media Bundle
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.custom.image
                - sonata.media.provider.audio
                - sonata.media.provider.file
                - sonata.media.provider.custom.vimeo
                - sonata.media.provider.custom.dailymotion
                - sonata.media.provider.custom.youtube
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        visual:
            providers:
                - sonata.media.provider.custom.image
                - sonata.media.provider.custom.vimeo
                - sonata.media.provider.custom.dailymotion
                - sonata.media.provider.custom.youtube
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        audio:
            providers:
                - sonata.media.provider.audio
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        image:
            providers:
                - sonata.media.provider.custom.image
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia