# Imports
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    # Custom configs files
    - { resource: config/framework.yml }
    - { resource: config/doctrine.yml }
    - { resource: config/twig.yml }
    - { resource: config/swiftmailer.yml }
    - { resource: config/ckeditor.yml }
    - { resource: config/sonata_admin.yml }
    - { resource: config/sonata_block.yml }
    - { resource: config/sonata_media.yml }
    - { resource: config/sonata_formatter.yml }

# Parameters
parameters:
    locale: fr
