security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    fdd:
                        password: $2y$10$XFSR0ipac.LgqT0PHnlBjOewMTmOAg7HfUoAnJRrLZM/.g5Lwbq8q
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
#            http_basic: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /admin/dashboard
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
