# Imports
imports:
    # Custom services files
    - { resource: services/sonata_entities.yml }
    - { resource: services/sonata_media_items.yml }
    - { resource: services/sonata_media_providers.yml }

parameters:
    sonata.media.admin.gallery.class: 'Application\Sonata\MediaBundle\Admin\GalleryAdmin'
    sonata.media.admin.gallery_has_media.class: 'Application\Sonata\MediaBundle\Admin\GalleryHasMediaAdmin'
    sonata.media.admin.book_has_media.class: 'Application\Sonata\MediaBundle\Admin\BookHasMediaAdmin'
    sonata.media.admin.media.class: 'Application\Sonata\MediaBundle\Admin\MediaAdmin'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
