<?php
namespace Application\Sonata\MediaBundle\Admin;

use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery;
use Sonata\MediaBundle\Admin\BaseMediaAdmin;

class MediaAdmin extends BaseMediaAdmin
{

    /**
     * {@inheritdoc}
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('name')
        ;
    }

    /**
     * {@inheritdoc}
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('name')
            ->add('context', null, [
                'show_filter' => false
            ])
        ;
    }

    public function createQuery($context = 'list')
    {
        // Store generated query
        $query = parent::createQuery($context);

        // Get Media Type Filter
        $mediaType = $this->getRequest()->get('mediaType');

        // If mediaType is defined, add provider param
        if(!is_null($mediaType)) {
            $query->andWhere(
                $query->expr()->eq($query->getRootAliases()[0] . '.providerName', ':my_param')
            );
        }

        // Audio medias
        if($mediaType === 'audio') {
            $query->setParameter('my_param', 'sonata.media.provider.audio');
        // Visual media
        } elseif ($mediaType === 'image' || $mediaType === 'visual') {
            // Image Provider
            $query->setParameter('my_param', 'sonata.media.provider.custom.image');
            // Add videos for visuals
            if($mediaType === 'visual') {
                // Youtube
                $query->orWhere(
                    $query->expr()->eq($query->getRootAliases()[0] . '.providerName', ':my_param2')
                );
                $query->setParameter('my_param2', 'sonata.media.provider.custom.youtube');
                // Dailymotion
                $query->orWhere(
                    $query->expr()->eq($query->getRootAliases()[0] . '.providerName', ':my_param3')
                );
                $query->setParameter('my_param3', 'sonata.media.provider.custom.dailymotion');
                // Vimeo
                $query->orWhere(
                    $query->expr()->eq($query->getRootAliases()[0] . '.providerName', ':my_param4')
                );
                $query->setParameter('my_param4', 'sonata.media.provider.custom.vimeo');
            }
        }

        return $query;
    }


    public function getPersistentParameters()
    {
        // Store parent function return array
        $return = parent::getPersistentParameters(); // TODO: Change the autogenerated stub

        // Reset context to default
        $return['context'] = 'default';
        return $return;
    }

}