<?php
namespace AppBundle\Entity;

use Application\Sonata\MediaBundle\Entity\Media;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class BookHasMedia
 * @package Application\Sonata\MediaBundle\Entity
 *
 * @ORM\Entity()
 */
class CoverImage extends BaseHasMedia
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        parent::prePersist(); // TODO: Change the autogenerated stub
        $this->setPosition(0);
    }

}