# Sonata MediaAdmin items
parameters:
    sonata.media.admin.gallery.class: 'Application\Sonata\MediaBundle\Admin\GalleryAdmin'
    sonata.media.admin.gallery_has_media.class: 'Application\Sonata\MediaBundle\Admin\GalleryHasMediaAdmin'
    sonata.media.admin.book_has_media.class: 'Application\Sonata\MediaBundle\Admin\BookHasMediaAdmin'
    sonata.media.admin.post_has_song.class: 'Application\Sonata\MediaBundle\Admin\PostHasSongAdmin'
    sonata.media.admin.post_has_media.class: 'Application\Sonata\MediaBundle\Admin\PostHasMediaAdmin'
    sonata.media.admin.media.class: 'Application\Sonata\MediaBundle\Admin\MediaAdmin'
    sonata.media.admin.song.class: 'Application\Sonata\MediaBundle\Admin\SongAdmin'

services:
    custom.media.admin.gallery:
        class: '%sonata.media.admin.gallery.class%'
        arguments:
            - ~
            - Application\Sonata\MediaBundle\Entity\Gallery
            - Application:GalleryAdmin
            - '@sonata.media.pool'
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Galleries}

    custom.media.admin.gallery_has_media:
        class: '%sonata.media.admin.gallery_has_media.class%'
        arguments:
            - ~
            - Application\Sonata\MediaBundle\Entity\GalleryHasMedia
            - Application:GalleryHasMediaAdmin
            - '@sonata.media.pool'
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin}

    custom.media.admin.book_has_media:
        class: '%sonata.media.admin.book_has_media.class%'
        arguments:
            - ~
            - AppBundle\Entity\BookHasMedia
            - Application:BookHasMediaAdmin
            - '@sonata.media.pool'
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin}

    custom.media.admin.post_has_song:
        class: '%sonata.media.admin.post_has_song.class%'
        arguments:
            - ~
            - AppBundle\Entity\PostHasSong
            - Application:PostHasSongAdmin
            - '@sonata.media.pool'
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin}

    custom.media.admin.post_has_media:
        class: '%sonata.media.admin.post_has_media.class%'
        arguments:
            - ~
            - AppBundle\Entity\PostHasMedia
            - Application:PostHasMediaAdmin
            - '@sonata.media.pool'
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin}

    custom.media.admin.media:
        class: '%sonata.media.admin.media.class%'
        arguments:
            - ~
            - Application\Sonata\MediaBundle\Entity\Media
            - Application:MediaAdmin
            - '@sonata.media.pool'
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Médias}
